#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: scripts/test [OPTION...]
    Build and run SFI services.

    Options:
      -p, --payments   include payment services
      -g, --gateway    include API gateway
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -p|--payments)
      payments="true"
      ;;

    -g|--gateway)
      gateway="true"
      ;;

    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
code ./ffc-sfi-apply-web && \
  code ./ffc-sfi-agreement-api && \
  code ./ffc-sfi-agreement-calculator && \
  code ./ffc-sfi-processing-web

if [ "${payments}" = "true" ]; then
  code ./ffc-sfi-payment-batch-processor && \
    code ./ffc-sfi-payment-enrichment && \
    code ./ffc-sfi-payments && \
    code ./ffc-sfi-payment-submission && \
    code ./ffc-sfi-payment-responses && \
    code ./ffc-sfi-payment-web
fi

if [ "${gateway}" = "true" ]; then
  code ./ffc-sfi-api-gateway
fi
