#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"
cd "${projectRoot}"
code ./ffc-sfi-apply-web && \
  code ./ffc-sfi-apply-api && \
  code ./ffc-sfi-siti-agri-mock && \
  code ./ffc-sfi-agreement-calculator && \
  code ./ffc-sfi-processing-web && \
  code ./ffc-sfi-payment-batch-processor && \
  code ./ffc-sfi-payments && \
  code ./ffc-sfi-payment-web && \
  code ./ffc-sfi-agreement-viewer
