#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"
cd "${projectRoot}"
cd ./ffc-sfi-apply-web && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfi-agreement-api && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfi-apply-api && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfi-agreement-calculator && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfi-processing-web && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfi-payment-batch-processor && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfi-payment-enrichment && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfi-payments && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfi-payment-submission && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfi-payment-web && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfi-agreement-viewer && \
  git checkout main && \
  git pull
